version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    environment:
      - DB_HOST=mysql-95ad972-thisiskingjethro-3be3.b.aivencloud.com
      - DB_PORT=21723
      - DB_USER=avnadmin
      - DB_PASS=AVNS__QSThIrRML7Pl85aWhR
      - DB_NAME=defaultdb
      - DB_SSL=true
