services:
  # The PHP Application (Deployed as a Web Service)
  - type: web
    name: fashion-designer-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: "mysql-95ad972-thisiskingjethro-3be3.b.aivencloud.com"
      - key: DB_PORT
        value: "21723"
      - key: DB_USER
        value: "avnadmin"
      - key: DB_PASS
        value: "AVNS__QSThIrRML7Pl85aWhR"
      - key: DB_NAME
        value: "defaultdb"
      - key: DB_SSL
        value: "true"
